<a href="https://colab.research.google.com/github/Garima-2702/Garima-2702/blob/Basic-of-python/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
!pip install pandas
import pandas as pd
print(pd.__version__)

1.5.3


In [ ]:
!apt-get -y install mysql-server
!service mysql start
!pip install mysql-connector-python
!sudo service mysql status
import mysql.connector

conn = mysql.connector.connect(user='root', password='root', unix_socket='/var/run/mysqld/mysqld.sock')

cursor = conn.cursor()


cursor.execute("CREATE DATABASE IF NOT EXISTS student")

# Switch to the 'library' database
cursor.execute("USE student")


cursor.execute('CREATE TABLE IF NOT EXISTS college (id INT(5), name CHAR(200), address VARCHAR(200));')
# cursor.execute("USE college")
cursor.close()
conn.close()



Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcgi-fast-perl libcgi-pm-perl libclone-perl libencode-locale-perl libfcgi-bin libfcgi-perl
  libfcgi0ldbl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl
  libhttp-message-perl libio-html-perl liblwp-mediatypes-perl libmecab2 libprotobuf-lite23
  liburi-perl mecab-ipadic mecab-ipadic-utf8 mecab-utils mysql-client-8.0 mysql-client-core-8.0
  mysql-server-8.0 mysql-server-core-8.0
Suggested packages:
  libdata-dump-perl libipc-sharedcache-perl libbusiness-isbn-perl libwww-perl mailx tinyca
The following NEW packages will be installed:
  libcgi-fast-perl libcgi-pm-perl libclone-perl libencode-locale-perl libfcgi-bin libfcgi-perl
  libfcgi0ldbl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl libhttp-date-perl
  libhttp-message-perl libio-html-perl liblwp-mediatypes-perl libmecab2 libprotobuf-l

In [ ]:
import mysql.connector


conn = mysql.connector.connect(user='root', password='root', unix_socket='/var/run/mysqld/mysqld.sock',database='student')

cursor = conn.cursor()


cursor.execute("CREATE DATABASE IF NOT EXISTS student")

# Switch to the 'library' database
cursor.execute("USE student")


cursor.execute('CREATE TABLE IF NOT EXISTS college (id INT(5), name CHAR(200), address VARCHAR(200));')
for i in range (3):
    id=int(input("Enter student id:")),
    name=input("Enter student name:"),
    address=input("Enter student address:")

cursor.execute('''
 INSERT INTO college(id,name,address) VALUES (%s, %s, %s)
''',(id,name,address) )
conn.commit()

print("Data entered successfully")
cursor.close()
conn.close()


KeyboardInterrupt: Interrupted by user

In [ ]:
import mysql.connector


conn = mysql.connector.connect(user='root', password='root', unix_socket='/var/run/mysqld/mysqld.sock',database='student')

cursor = conn.cursor()

cursor.execute("CREATE DATABASE IF NOT EXISTS library")

# Switch to the 'library' database
cursor.execute("USE library")

# Create the 'books' table
cursor.execute('''
CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    author VARCHAR(255),
    year_published INT
)
''')

# Always remember to close the cursor and connection when done
cursor.close()
conn.close()

In [ ]:
import mysql.connector

# Connect to the MySQL server and the 'library' database
conn = mysql.connector.connect(user='root', password='root',unix_socket='/var/run/mysqld/mysqld.sock' , database='library')
cursor = conn.cursor()

books_data = [
    ("To Kill a Mockingbird", "Harper Lee", 1960),
    ("1984", "George Orwell", 1949),
    ("The Great Gatsby", "F. Scott Fitzgerald", 1925)
]

# Insert data using the cursor
cursor.executemany('''
INSERT INTO books (title, author, year_published) VALUES (%s, %s, %s)
''', books_data)
# Commit the changes
conn.commit()
cursor.execute("SELECT * FROM books")

# Fetch all the results
records = cursor.fetchall()

# Print the records
for record in records:
    print(record)

# Close the cursor and connection
cursor.close()
conn.close()

(1, 'To Kill a Mockingbird', 'Harper Lee', 1960)
(2, '1984', 'George Orwell', 1949)
(3, 'The Great Gatsby', 'F. Scott Fitzgerald', 1925)


In [ ]:
from tabulate import tabulate
import pandas as pd
conn = mysql.connector.connect(user='root', password='root', unix_socket='/var/run/mysqld/mysqld.sock',database='library')
query = "SELECT * FROM books"
df = pd.read_sql(query, conn)


df = df.dropna(how="any")
x=pd.DataFrame(df)
print(tabulate(x,headers='key',tablefmt='psql'))




+----+----+------------------+---------------------+------+
|    |    | k                | e                   |    y |
|----+----+------------------+---------------------+------|
|  1 |  2 | 1984             | George Orwell       | 1949 |
|  2 |  3 | The Great Gatsby | F. Scott Fitzgerald | 1925 |
+----+----+------------------+---------------------+------+


<ipython-input-9-58150d6c886e>:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)


In [ ]:
!mysql -e"update library.books set year_published=NULL where author='Harper Lee'"
!mysql -e "select * from library.books"

+----+-----------------------+---------------------+----------------+
| id | title                 | author              | year_published |
+----+-----------------------+---------------------+----------------+
|  1 | To Kill a Mockingbird | Harper Lee          |           NULL |
|  2 | 1984                  | George Orwell       |           1949 |
|  3 | The Great Gatsby      | F. Scott Fitzgerald |           1925 |
+----+-----------------------+---------------------+----------------+


In [ ]:
!pip install urllib3

In [ ]:
import urllib.request

In [ ]:
dir(urllib)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'error',
 'parse',
 'request',
 'response']

In [ ]:
dir(urllib.request)

['AbstractBasicAuthHandler',
 'AbstractDigestAuthHandler',
 'AbstractHTTPHandler',
 'BaseHandler',
 'CacheFTPHandler',
 'ContentTooShortError',
 'DataHandler',
 'FTPHandler',
 'FancyURLopener',
 'FileHandler',
 'HTTPBasicAuthHandler',
 'HTTPCookieProcessor',
 'HTTPDefaultErrorHandler',
 'HTTPDigestAuthHandler',
 'HTTPError',
 'HTTPErrorProcessor',
 'HTTPHandler',
 'HTTPPasswordMgr',
 'HTTPPasswordMgrWithDefaultRealm',
 'HTTPPasswordMgrWithPriorAuth',
 'HTTPRedirectHandler',
 'HTTPSHandler',
 'MAXFTPCACHE',
 'OpenerDirector',
 'ProxyBasicAuthHandler',
 'ProxyDigestAuthHandler',
 'ProxyHandler',
 'Request',
 'URLError',
 'URLopener',
 'UnknownHandler',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_cut_port_re',
 '_ftperrors',
 '_have_ssl',
 '_localhost',
 '_noheaders',
 '_opener',
 '_parse_proxy',
 '_proxy_bypass_macosx_sysconf',
 '_randombytes',
 '_safe_gethostbyname',
 '_splitattr',
 '_sp

In [ ]:
from urllib.request import urlopen

In [ ]:
shakespeare = 'https://www.geeksforgeeks.org/how-to-print-an-entire-pandas-dataframe-in-python/'
print( type(shakespeare) )
print( shakespeare + '  -  ' + shakespeare)
shakespeare = urlopen('https://www.geeksforgeeks.org/how-to-print-an-entire-pandas-dataframe-in-python/')


<class 'str'>
https://www.geeksforgeeks.org/how-to-print-an-entire-pandas-dataframe-in-python/  -  https://www.geeksforgeeks.org/how-to-print-an-entire-pandas-dataframe-in-python/


In [ ]:
print( type(shakespeare) )

<class 'http.client.HTTPResponse'>


In [ ]:
import requests

response = requests.get('https://reqres.in/api/users?page=2')
print(response.text)

{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free, contributions towards se

In [ ]:
import requests
from urllib.request import urlopen

url='https://www.geeksforgeeks.org/how-to-print-an-entire-pandas-dataframe-in-python/'
print(url)

url = urlopen('https://www.geeksforgeeks.org/how-to-print-an-entire-pandas-dataframe-in-python/')
print(url.status)



https://www.geeksforgeeks.org/how-to-print-an-entire-pandas-dataframe-in-python/
200


In [ ]:
from urllib.request import Request, urlopen

req = Request(
    url='https://reqres.in/api/users?page=2',
    headers={'User-Agent': 'Mozilla/5.0'}
)
webpage = urlopen(req).read()
print(webpage)

b'{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free, contributions towards 

In [ ]:
import requests

data = {'key': 'value'}
response = requests.post('https://reqres.in/api/users?page=2', data=data)
print(response.text)
print(response.status_code)

{"key":"value","id":"481","createdAt":"2024-02-14T04:58:12.620Z"}
201


In [ ]:
import requests
import json

req = Request(
    url='https://reqres.in/api/users?page=2',
    headers={'User-Agent': 'Mozilla/5.0'}
)
webpage = urlopen(req).read()
print(webpage)
response = requests.get('https://reqres.in/api/users?page=2')
if response.status_code ==200:
  data_array=response.json().get('data',[])
  for obj in data_array:
    email = obj.get('email')
    if email:
      print(f"Email: {email}")
    else:
      print("no email is found")

  print("Converted to JSON")


b'{"page":2,"per_page":6,"total":12,"total_pages":2,"data":[{"id":7,"email":"michael.lawson@reqres.in","first_name":"Michael","last_name":"Lawson","avatar":"https://reqres.in/img/faces/7-image.jpg"},{"id":8,"email":"lindsay.ferguson@reqres.in","first_name":"Lindsay","last_name":"Ferguson","avatar":"https://reqres.in/img/faces/8-image.jpg"},{"id":9,"email":"tobias.funke@reqres.in","first_name":"Tobias","last_name":"Funke","avatar":"https://reqres.in/img/faces/9-image.jpg"},{"id":10,"email":"byron.fields@reqres.in","first_name":"Byron","last_name":"Fields","avatar":"https://reqres.in/img/faces/10-image.jpg"},{"id":11,"email":"george.edwards@reqres.in","first_name":"George","last_name":"Edwards","avatar":"https://reqres.in/img/faces/11-image.jpg"},{"id":12,"email":"rachel.howell@reqres.in","first_name":"Rachel","last_name":"Howell","avatar":"https://reqres.in/img/faces/12-image.jpg"}],"support":{"url":"https://reqres.in/#support-heading","text":"To keep ReqRes free, contributions towards 

In [ ]:

import requests
import json

url = 'https://reqres.in/api/users'
headers = {'User-Agent': 'Mozilla/5.0'}
data = {'name': 'John Doe', 'job': 'Software Engineer'}
response = requests.post(url, headers=headers, json=data)

if response.status_code == 201:
    created_data = response.json()
    print(f"User created with id: {created_data['id']}")
    print(f"Converted to JSON: {json.dumps(created_data, indent=4)}")
else:
    print(f"Request failed with status code {response.status_code}")

User created with id: 506
Converted to JSON: {
    "name": "John Doe",
    "job": "Software Engineer",
    "id": "506",
    "createdAt": "2024-02-15T04:40:35.610Z"
}


In [2]:
import requests
import json


url='https://coinmarketcap.com/currencies/bitcoin/',


webpage = urlopen('https://coinmarketcap.com/currencies/bitcoin/')
print(webpage)
response = requests.get('https://coinmarketcap.com/currencies/bitcoin/')
# if response.status_code ==200:
#   data_array=response.json().get('data',[])
#   for obj in data_array:
#     email = obj.get('market cap')
#     if email:
#       print(f"Market cap: {email}")
#     else:
#       print("no market value is found")

print("Converted to JSON")


NameError: name 'urlopen' is not defined

In [35]:
import numpy as np

import sklearn as sk
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

home=np.array([100,200,300,400,500,600,700,800,900,1000])

price=np.array([20000,40000,60000,80000,100000,120000,140000,160000,180000,200000])


print(home)
print(price)
home_train, home_test, price_train, price_test = train_test_split( home, price, test_size=0.5, random_state=4,shuffle=False)
print(home_train)
print(home_test)
print(price_train)
print(price_test)

reg = LinearRegression().fit(home_train.reshape(-1,1), price_train.reshape(-1,1))
print(reg.score(home_test.reshape(-1,1), price_test.reshape(-1,1)))
reg.predict(home_test.reshape(-1,1))


[ 100  200  300  400  500  600  700  800  900 1000]
[ 20000  40000  60000  80000 100000 120000 140000 160000 180000 200000]
[100 200 300 400 500]
[ 600  700  800  900 1000]
[ 20000  40000  60000  80000 100000]
[120000 140000 160000 180000 200000]
1.0


array([[120000.],
       [140000.],
       [160000.],
       [180000.],
       [200000.]])